from odoo import api, fields, models
from odoo.exceptions import UserError, ValidationError



class CustomReports(models.Model):
    _name = 'custom.reports'




